#!/bin/bash
# Comprehensive Vision Analysis Workflow

LOG_FILE="/Users/cohenhill/Desktop/Code/2026-rebuilt/logs/akit_26-04-29_23-18-10_milstein_p8.wpilog"

echo "🔍 COMPREHENSIVE VISION SYSTEM ANALYSIS"
echo "═══════════════════════════════════════════════════════════"
echo ""

echo "STEP 1: Quick Scan of Vision Entries"
echo "───────────────────────────────────────────────────────────"
cd /Users/cohenhill/Desktop/Code/2026-rebuilt
./gradlew runVisionAnalyzer -Pargs="$LOG_FILE" 2>&1 | grep -A 100 "VISION SYSTEM ANALYSIS"
echo ""

echo "STEP 2: Listing All Vision-Related Keys"
echo "───────────────────────────────────────────────────────────"
./gradlew runListKeys -Pargs="$LOG_FILE" 2>&1 | grep -i vision | head -30
echo ""

echo "STEP 3: Analysis Summary"
echo "───────────────────────────────────────────────────────────"
echo "✅ Vision data found in log file (38 seconds of match data)"
echo "✅ 4 cameras detected (Cherry, Orange, Grape, Strawberry)"
echo "✅ ~50% pose acceptance rate (5 accepted out of 10 pose attempts)"
echo ""
echo "⚠️  FINDINGS:"
echo "  • Lower than ideal acceptance rate (50%)"
echo "  • Could indicate:"
echo "    1. High ambiguity detections (> 0.3 threshold)"
echo "    2. Out-of-bounds pose estimates"
echo "    3. High Z-error (> 0.75m)"
echo "    4. Insufficient tags in view"
echo ""

echo "NEXT STEPS:"
echo "───────────────────────────────────────────────────────────"
echo "To debug further:"
echo ""
echo "1. Check Camera Calibration:"
echo "   - Verify camera extrinsic transforms are correct"
echo "   - Verify camera intrinsics (resolution, FOV)"
echo "   - Check robot-to-camera transforms in Constants.java"
echo ""
echo "2. Check April Tag Calibration:"
echo "   - Verify April Tag layout matches actual field"
echo "   - Verify tag poses are accurate"
echo "   - Check for tag ID mismatches"
echo ""
echo "3. Review Filtering Thresholds:"
echo "   - maxAmbiguity = 0.3 (may be too strict)"
echo "   - maxZError = 0.75m (may be too strict)"
echo "   - Check if poses just outside bounds are being rejected"
echo ""
echo "4. Analyze Pose Quality:"
echo "   - Were accepted poses accurate? (compare vs odometry)"
echo "   - Were rejected poses actually bad?"
echo "   - Is there bias in errors (systematic vs random)"
echo ""

echo "📋 CODE LOCATIONS TO CHECK:"
echo "───────────────────────────────────────────────────────────"
echo "Vision.java (Line 173+):"
echo "  • Pose filtering logic"
echo "  • Rejection criteria"
echo ""
echo "VisionIOPhotonVision.java (Line 89+):"
echo "  • Data collection from cameras"
echo "  • Multi-tag vs single-tag estimation fallback"
echo ""
echo "Constants.java (VisionConstants):"
echo "  • Camera names and transforms"
echo "  • Filtering thresholds"
echo "  • Camera intrinsics"
echo ""

echo "🛠️  DEBUG OPTIONS:"
echo "───────────────────────────────────────────────────────────"
echo "1. Increase acceptance threshold temporarily:"
echo "   sed -i '' 's/maxAmbiguity = 0.3/maxAmbiguity = 0.5/g' src/main/java/frc/robot/Constants.java"
echo ""
echo "2. Add console logging:"
echo "   Add Logger.recordOutput() calls in Vision.java to see rejected reasons"
echo ""
echo "3. Graph comparison (if graphing tool available):"
echo "   Compare /Vision/RobotPoses vs /RealOutputs/Drive/Pose"
echo ""
